4:1 error: foo already exists in context
