_xi_out_of_bounds called